### ISSUE TITLE
Wrangler throws an error during start

### ISSUE THREAD

**Issue by 0xi4o** [evoluhq/evolu#485]
I've a Remix app using Evolu that I want to deploy to Cloudflare Pages. When I run `wrangler pages dev ./build/client` I get this error:

```
✘ [ERROR] service core:user:worker: Uncaught Error: (FiberFailure) (FiberFailure) Error: Disallowed operation called within global scope. Asynchronous I/O (ex: fetch() or connect()), setting a timeout, and generating random values are not allowed within global scope. To fix this error, perform this operation within a handler. https://developers.cloudflare.com/workers/runtime-apis/handlers/

    at null.<anonymous> (ix5qrvh0o2.js:63941:22) in fiberFailure
    at null.<anonymous> (ix5qrvh0o2.js:63882:15)
    at null.<anonymous> (ix5qrvh0o2.js:70642:51) in runSync
    at null.<anonymous> (ix5qrvh0o2.js:48267:25) in pipeArguments
    at null.<anonymous> (ix5qrvh0o2.js:53408:16) in pipe
    at null.<anonymous> (ix5qrvh0o2.js:98975:77) in createEvolu
    at null.<anonymous> (ix5qrvh0o2.js:101318:13) in ../build/server/index.js
    at null.<anonymous> (ix5qrvh0o2.js:10:56) in __init
    at null.<anonymous> (ix5qrvh0o2.js:101574:5) in [[path]].ts
    at null.<anonymous> (ix5qrvh0o2.js:10:56) in __init


✘ [ERROR] MiniflareCoreError [ERR_RUNTIME_FAILURE]: The Workers runtime failed to start. There is likely additional logging output above.
```

Repo for reproducing this error: https://github.com/0xi4o/remix-cloudflare-pages

**Comment by steida** [comment]
Thank you for reporting that. I will take a look in a few days.

**Comment by steida** [comment]
Closing as this is no longer relevant—the new Evolu launches tomorrow. Feel free to reopen if it becomes relevant with the new Evolu.
